In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [7]:
df2 = pd.DataFrame(data_list)

In [8]:
columns = ["Name","Age","City","Salary"]

In [9]:
df2 = pd.DataFrame(data_list,columns = columns)

In [10]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

__Selection And Indexing Of Column__

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [15]:
df2["Designation"] = ["Doctor","Engineer","Engineer","Doctor"]

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

In [18]:
df2.drop("Designation",axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

__Removing a column__

In [20]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
2  Peter   29  Berlin   62000    Engineer
3  Linda   42  London   85000      Doctor

In [21]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

In [27]:
df2.drop(["Name","Age"],axis = 1)

       City  Salary Designation
0  New York   65000      Doctor
1     Paris   70000    Engineer
2    Berlin   62000    Engineer
3    London   85000      Doctor

In [28]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

In [29]:
df2.drop("Designation",axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

In [31]:
df2.drop("Designation",axis = 1 , inplace = True )

In [32]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [34]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

__Removing a Rows__

In [39]:
df2

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

__Selecting a rows__

In [42]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [46]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [47]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [48]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
df.loc[[0,1,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [50]:
df.loc[[0]]

   Name  Age      City  Salary
0  John   28  New York   65000

__Selecting Subsets of rows and columns__

In [52]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [53]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [54]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [55]:
df.loc[[2]][["Name"]]

    Name
2  Peter

__Conditional Selection__

In [56]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [58]:
# I only want to see those people whose age is above 30

In [61]:
df[df["Age"] > 30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

#I only want people whose age is above 30 and their city must be Paris

In [69]:
df[ (df["Age"] > 30) & (df["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [70]:
df[ (df["Age"] > 30) & (df["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000