In [4]:
import numpy as np
import pandas as pd

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [5]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
#Group by Category and Calculate the sum of Sales

In [10]:
cat = df.groupby("Category")['Sales'].sum()

In [14]:
# for i ,v in cat :
#     print(i)
#     print(v)

In [13]:
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [15]:
#Group by Store and Calculate the sum of Sales :

In [16]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [18]:
bat = df.groupby("Store")

In [19]:
for i,v in bat :
    print(i)
    print(v)

S1
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
4        A    S1    120         8 2023-01-05
7        B    S1    300        25 2023-01-08
S2
  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07

In [20]:
bat = df.groupby("Store")["Sales"].sum()

In [21]:
bat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [22]:
tat = df.groupby("Sales")["Quantity"].sum()

In [23]:
tat

Sales
100    10
120     8
150    12
180    20
200    30
250    18
300    25
Name: Quantity, dtype: int64

In [24]:
#Group by Multiple Columns :

df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [25]:
gmc = df.groupby(["Category","Store"])["Sales"].sum()

In [26]:
gmc

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

__Aggregation__

In [27]:
df["Sales"].mean()

np.float64(187.5)

In [32]:
df['Sales'].agg(['sum','mean','min','max','count','std'])

sum      1500.000000
mean      187.500000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64